# Use an official Python 3.12 runtime as a parent image
FROM continuumio/anaconda3

# Set the working directory in the container
WORKDIR /app

# Install Git
RUN apt-get update && apt-get install -y git && apt-get clean && rm -rf /var/lib/apt/lists/*

# Clone the repository
RUN git clone https://github.com/leviathanaxeislit/AiWorkforcePlanningTools.git .

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    libpoppler-cpp-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Expose port 8501 for Streamlit
EXPOSE 8501

# Command to run the app
ENTRYPOINT ["streamlit", "run"]

CMD ["app.py", "--server.port=8501", "--server.address=0.0.0.0"]
