# Use an official Python 3.12 runtime as a parent image
FROM python:3.12-bookworm

# Set the working directory in the container
WORKDIR /app

# Clone the repository
COPY models/ models/
COPY pages/ pages/
COPY styles/ styles/
COPY .dockerignore .
COPY .gitignore .
COPY app.py .
COPY DockerFile .
COPY LICENSE .
COPY README.md .
COPY requirements.txt .


# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    libpoppler-cpp-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
RUN pip install -r requirements.txt

# Expose port 8501 for Streamlit
EXPOSE 8501

# Command to run the app
ENTRYPOINT ["streamlit", "run"]

CMD ["app.py", "--server.port=8501", "--server.address=0.0.0.0"]

