[theme]

font="sans serif"
primaryColor="maroon"  # Light Blue (Interactive Elements)
backgroundColor="#e0e2ed" # White (Main Background)
secondaryBackgroundColor="#a0b9e0" # Light Gray (Secondary Background)
textColor="" # Dark Gray (Text Color)

[client]
showSidebarNavigation = false
